### ISSUE TITLE
Failed to checkpoint container - cuda-checkpoint: Interrupted system call

### ISSUE THREAD

**Issue by zhuangqh** [NVIDIA/cuda-checkpoint#26]
## Description

I am checkpointing a pytorch container using containerd tool.
```
ctr -n k8s.io c checkpoint --task --rw --image-path /mnt/ckpt/ tuning ckimg
```
Got this error from criu dump log
```
(00.004206) cg: Set 1 is criu one
(00.004211) plugin: `cuda_plugin' hook 10 -> 0x753e11bb86f3
(00.020701) cuda_plugin: pausing devices on pid 1801089
(10.004259) Error (criu/cr-dump.c:1791): Timeout reached. Try to interrupt: 0
(10.004324) Error (cuda_plugin.c:139): cuda_plugin: Unable to read output of cuda-checkpoint: Interrupted system call
(10.005493) Error (cuda_plugin.c:457): cuda_plugin: PAUSE_DEVICES failed with
(11.004352) Error (criu/cr-dump.c:1791): Timeout reached. Try to interrupt: 1
(11.004398) Error (cuda_plugin.c:139): cuda_plugin: Unable to read output of cuda-checkpoint: Interrupted system call
(11.005243) Error (cuda_plugin.c:472): cuda_plugin: Failed to unlock process status , pid 1801089 may hang
(11.005281) net: Unlock network
(11.005293) cuda_plugin: finished cuda_plugin stage 0 err -1
(11.005354) Unfreezing tasks into 1
(11.005359)     Unseizing 1801089 into 1
(11.005364) Error (compel/src/lib/infect.c:418): Unable to detach from 1801089: No such process
(11.005378) Error (criu/cr-dump.c:2111): Dumping FAILED.
```

If I manually bypass the check here, checkpoint will be successful. And this image can be restored successfully.
https://github.com/checkpoint-restore/criu/blob/criu-dev/plugins/cuda/cuda_plugin.c#L426
```c
	// task_state = get_cuda_state(restore_tid);
        task_state = CUDA_TASK_CHECKPOINTED;
	if (task_state == CUDA_TASK_UNKNOWN) {
		pr_err("Failed to get CUDA state for PID %d\n", restore_tid);
		return -1;
	}
```

## Env

nvidia 570 driver
latest criu.
latest cuda-checkpoint tool

**Comment by rst0git** [comment]
@zhuangqh This problem should be fixed in https://github.com/checkpoint-restore/criu/pull/2547.
Could you try upgrading CRIU to v4.1? Alternatively, you can try adding `timeout=300` in `/etc/criu/runc.conf`.

**Comment by zhuangqh** [comment]
> [@zhuangqh](https://github.com/zhuangqh) This problem should be fixed in [checkpoint-restore/criu#2547](https://github.com/checkpoint-restore/criu/pull/2547). Could you try upgrading CRIU to v4.1? Alternatively, you can try adding `timeout=300` in `/etc/criu/runc.conf`.

I've included your commit. I can still get this error after adding timeout=300 to /etc/criu/runc.conf.

Do you need to manually toggle container process pid before dump?

**Comment by rst0git** [comment]
> Do you need to manually toggle container process pid before dump?

The CRIU CUDA plugin obtains the current state of CUDA tasks (with `task_state = get_cuda_state(restore_tid)`). The task could be in one of the following states: `running`, `locked`, or `checkpointed`:
- if a task is in a *running* state, the plugin will perform *lock* and *checkpoint* actions.
- if a task is in a *locked* state, the plugin will perform only *checkpoint* action.
- if a task is in a *checkpointed* state, the plugin will skip this task and continue.

The state of CUDA tasks is also used for the `--leave-running` functionality (used by default with Kubernetes) to ensure that CUDA tasks remain in their original state at the end of the checkpoint operation.

**Comment by avagin** [comment]
@zhuangqh could you attach a dump log grenerate by criu with https://github.com/checkpoint-restore/criu/pull/2547
